Attribute VB_Name = "LANGUAGE_TYPE"

Public Type Any
End Type

Public Type Numeric
End Type

Public Type Byte
End Type

Public Type Integer
End Type

Public Type Long
End Type

Public Type String
End Type

Public Type Single
End Type

Public Type Double
End Type

Public Type Currency
End Type

Public Type Date
End Type

Public Type Boolean
End Type

Public Type Object
End Type

Public Type Variant
End Type

Public Type Void
End Type

Public Type Err
	LastDllError As Object
End Type

Public Type App
End Type



Public Type OLE_COLOR
End Type
